### ISSUE TITLE
SD-JWT implementation 

### ISSUE THREAD

**Issue by andrea-dintino** [dyne/Zenroom#717]
Selective Disclosure JWT (SD-JWT) is still a draft, but it's required by eIDAS 2.0 and EUDI-ARF, see  https://digital-strategy.ec.europa.eu/en/library/european-digital-identity-wallet-architecture-and-reference-framework  (so this is a requirement for DIDroom).

```[tasklist]
### Tasks
- [ ] Research documentation: https://datatracker.ietf.org/doc/draft-ietf-oauth-selective-disclosure-jwt/
- [ ] identify cryptography used
- [ ] identify data formats used
- [ ] implement sample W3C-VC creation/verification with SD-JWT
- [ ] Implement Zencode and tests
```

List of implementations: https://github.com/oauth-wg/oauth-selective-disclosure-jwt

**Comment by jaromil** [comment]
moved to #732
